name: camsharelite
description: "CamShare Lite — câmera ao vivo em stream MJPEG na rede local (LAN), sem conta e sem nuvem."
publish_to: 'none'
version: 1.0.2+4

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.6
  provider: ^6.1.2
  network_info_plus: ^5.0.3
  image: ^4.2.0
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
